sudo: false
language: go
branches:
  only:
    - master

go:
  - 1.4.3
  - 1.5.4
  - 1.6.3
  - 1.7.3
  - tip

env:
  global:
    - GOARCH=amd64
    - TRAVISTEST=true

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci